version: '3'

services:
  JavaScript:
    image: "node"
    volumes:
      - ./js:/app
    command: node /app/main.js
  cpp:
    build: "cpp"
    volumes:
      - ./cpp:/app
    command: sh -c "g++ -o /tmp/main /app/main.cpp && /tmp/main"
